Indian Kids Screen Time

In [329]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [330]:
file = pd.read_csv(r"C:\Users\grahu\Desktop\screensense\data\raw\data.csv")

In [331]:
df=pd.DataFrame(file)

In [332]:
df.head()

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,NaN,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban

In [333]:
df.shape

(9712, 8)

In [334]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   str
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   str
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     6494 non-null   str
 7   Urban_or_Rural                     9712 non-null   str
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 540.7 KB

In [335]:
df.describe()

,Age,Avg_Daily_Screen_Time_hr,Educational_to_Recreational_Ratio
count,9712.000000,9712.000000,9712.000000
mean,12.979201,4.352837,0.427226
std,3.162437,1.718232,0.073221
min,8.000000,0.000000,0.300000
25%,10.000000,3.410000,0.370000
50%,13.000000,4.440000,0.430000
75%,16.000000,5.380000,0.480000
max,18.000000,13.890000,0.600000

In [336]:
df.isnull().sum()

Age                                     0
Gender                                  0
Avg_Daily_Screen_Time_hr                0
Primary_Device                          0
Exceeded_Recommended_Limit              0
Educational_to_Recreational_Ratio       0
Health_Impacts                       3218
Urban_or_Rural                          0
dtype: int64

In [337]:
df.duplicated().sum()

np.int64(44)

DATA CLEANING

In [338]:
#health impacts have missing values we will change it to "None"
df['Health_Impacts']=df['Health_Impacts'].fillna("None")

In [339]:
#checking for null values again
df.isnull().sum()

Age                                  0
Gender                               0
Avg_Daily_Screen_Time_hr             0
Primary_Device                       0
Exceeded_Recommended_Limit           0
Educational_to_Recreational_Ratio    0
Health_Impacts                       0
Urban_or_Rural                       0
dtype: int64

Standerdisze categories

In [340]:
#Gender 
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [341]:
df['Gender']=df['Gender'].str.strip().str.title()

In [342]:
#cheking for primary device used by the users
df['Primary_Device'].unique()

<StringArray>
['Smartphone', 'Laptop', 'TV', 'Tablet']
Length: 4, dtype: str

In [ ]:
#removing whitespace and converting to title case
df['Primary_Device']=df['Primary_Device'].str.strip().str.title()

In [344]:
#checking if urban or rural users are more
df['Urban_or_Rural'] = df['Urban_or_Rural'].str.strip().str.title()

Removing invalid rows

In [345]:
#age validation
df= df[(df['Age'] >= 5) & (df['Age'] <= 18)]

In [346]:
#screen time validation values cant be negative
df = df[(df['Avg_Daily_Screen_Time_hr'] >=0) & (df['Avg_Daily_Screen_Time_hr'] <= 24)]

In [347]:
#education to recreation ratio validation
df=df[df['Educational_to_Recreational_Ratio'] >= 0]

In [348]:
df=df.drop_duplicates() #removing duplicates

Checking again

In [349]:
df.info()

<class 'pandas.DataFrame'>
Index: 9668 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9668 non-null   int64
 1   Gender                             9668 non-null   str
 2   Avg_Daily_Screen_Time_hr           9668 non-null   float64
 3   Primary_Device                     9668 non-null   str
 4   Exceeded_Recommended_Limit         9668 non-null   bool
 5   Educational_to_Recreational_Ratio  9668 non-null   float64
 6   Health_Impacts                     9668 non-null   str
 7   Urban_or_Rural                     9668 non-null   str
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 613.7 KB

In [350]:
df.shape

(9668, 8)

In [351]:
df.describe()

,Age,Avg_Daily_Screen_Time_hr,Educational_to_Recreational_Ratio
count,9668.000000,9668.000000,9668.000000
mean,12.992760,4.367780,0.427028
std,3.158931,1.703002,0.073185
min,8.000000,0.000000,0.300000
25%,10.000000,3.427500,0.370000
50%,13.000000,4.440000,0.430000
75%,16.000000,5.380000,0.480000
max,18.000000,13.890000,0.600000

Feature engineering

In [352]:
#creating age bands
df['Age_Band'] = pd.cut(df['Age'], bins=[0, 5,9,13, 17, 18], labels=['3-5', '6-9', '10-13', '14-17', '18+'])

df['Age_Band'].value_counts().sort_index()
#df['Age_Band'] = pd.cut(df['Age'], bins=[5, 8, 12, 15, 18], labels=['5-8', '9-12', '13-15', '16-18'])

Age_Band
3-5         0
6-9      1775
10-13    3503
14-17    3551
18+       839
Name: count, dtype: int64

In [353]:
df['Screen_Time_Level'] = pd.cut(
    df['Avg_Daily_Screen_Time_hr'],
    bins=[0, 2, 4, 6, 8, 24],
    labels=['Low', 'Moderate', 'High', 'Very High', 'Extreme'],
)

In [354]:
df[['Age','Age_Band','Avg_Daily_Screen_Time_hr','Screen_Time_Level']].head()

   Age Age_Band  Avg_Daily_Screen_Time_hr Screen_Time_Level
0   14    14-17                      3.99          Moderate
1   11    10-13                      4.61              High
2   18      18+                      3.73          Moderate
3   15    14-17                      1.21               Low
4   12    10-13                      5.89              High

In [355]:
df

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural,Age_Band,Screen_Time_Level
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban,14-17,Moderate
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban,10-13,High
2,18,Female,3.73,Tv,True,0.32,Poor Sleep,Urban,18+,Moderate
3,15,Female,1.21,Laptop,False,0.39,None,Urban,14-17,Low
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban,10-13,High
...,...,...,...,...,...,...,...,...,...,...
9707,17,Male,3.26,Smartphone,True,0.44,Poor Sleep,Urban,14-17,Moderate
9708,17,Female,4.43,Smartphone,True,0.40,Poor Sleep,Rural,14-17,High
9709,16,Male,5.62,Smartphone,True,0.39,"Poor Sleep, Eye Strain, Anxiety",Rural,14-17,High
9710,17,Male,5.60,Tv,True,0.43,Poor Sleep,Urban,14-17,High
9711,15,Female,6.12,Tv,True,0.33,Anxiety,Urban,14-17,Very High

In [356]:
df.to_csv('Preprocessed_data.csv', index=False)